[package]
name = "mason-core"
version = "0.0.0"
authors = ["Ryan Leckey <leckey.ryan@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "Shared types and traits for Mason."
edition = "2018"

[dependencies]
