[package]
name = "sqlx-postgres"
version = "0.1.0-pre"
edition = "2018"
authors = ["Ryan Leckey <ryan@launchbadge.com>"]

[dependencies]
sqlx-rt = { path = "../sqlx-rt", version = "0.1.1" }
sqlx-core = { package = "sqlx-core2", path = "../sqlx-core2", version = "0.4.0-beta.2" }
bytes = "0.5.6"
md-5 = "0.9.1"
atoi = "0.3.2"
memchr = "2.3.3"
whoami = "0.9.0"
url = "2.1.1"
futures-core = "0.3.5"
futures-util = "0.3.5"
base64 = "0.12.3"
