[package]
name = "mason-postgres-protocol"
version = "0.0.0"
authors = ["Ryan Leckey <leckey.ryan@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "Provides standalone encoding and decoding of the PostgreSQL v3 wire protocol."
edition = "2018"

[dependencies]
byteorder = "1.3.1"
bytes = "0.4.12"
memchr = "2.2.0"
md-5 = "0.8.0"
itoa = "0.4.4"

[dev-dependencies]
matches = "0.1.8"
criterion = "0.2"

[[bench]]
name = "decode"
harness = false

[[bench]]
name = "encode"
harness = false
