[package]
name = "sqlx-test"
version = "0.0.0"
edition = "2018"
publish = false
description = "Internal crate providing test utilities for testing SQLx database drivers."

[dependencies]
tokio = { version = "1.0", features = ["full"] }
futures-util = "0.3.8"
anyhow = "1.0.37"
