[workspace]
default-members = ["sqlx"]
members = [
    "sqlx-core",
    "sqlx-mysql",
    "sqlx",

    # examples
    "examples/quickstart/mysql+blocking",
    "examples/quickstart/mysql+async-std",
    "examples/quickstart/mysql+tokio"
]
