[workspace]
members = [
    ".",
    "mason-core",
    "mason-postgres-protocol",
    "mason-postgres",
]

[package]
name = "mason"
version = "0.0.0"
authors = ["Ryan Leckey <leckey.ryan@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "Asynchronous and expressive database client in pure Rust."
edition = "2018"

[dependencies]
runtime = "=0.3.0-alpha.4"
mason-core = { path = "mason-core" }
mason-postgres = { path = "mason-postgres" }
failure = "0.1"
env_logger = "0.6.1"
bytes = "0.4.12"

[profile.bench]
lto = true
