[package]
name = "sqlx"
version = "0.1.1-pre"
license = "MIT OR Apache-2.0"
description = "The Rust SQL Toolkit."
edition = "2018"
authors = [
    "Ryan Leckey <leckey.ryan@gmail.com>"
]

[features]
default = []
unstable = []
postgres = []
mariadb = []

[dependencies]
async-stream = "0.1.1"
async-trait = "0.1.11"
bitflags = "1.1.0"
byteorder = { version = "1.3.2", default-features = false }
bytes = "0.4.12"
crossbeam-queue = "0.1.2"
crossbeam-utils = { version = "0.6.6", default-features = false }
futures-channel-preview = "0.3.0-alpha.18"
futures-core-preview = "0.3.0-alpha.18"
futures-util-preview = "0.3.0-alpha.18"
log = "0.4.8"
md-5 = "0.8.0"
memchr = "2.2.1"
tokio = { version = "0.2.0-alpha.4", default-features = false, features = [ "tcp" ] }
url = "2.1.0"
uuid = { version = "0.8.1", optional = true }

[dev-dependencies]
matches = "0.1.8"
tokio = { version = "0.2.0-alpha.4", default-features = false, features = [ "rt-full" ] }
sqlx-macros = { path = "sqlx-macros/" }

[profile.release]
lto = true
codegen-units = 1

[[test]]
name = "sql-macro-test"
required-features = ["uuid"]
