[workspace]
members = [
    ".",
    "sqlx-core",
    "sqlx-macros",
    "examples/realworld"
]

[package]
name = "sqlx"
version = "0.1.1-pre"
license = "MIT OR Apache-2.0"
description = "The Rust SQL Toolkit."
edition = "2018"
authors = [
    "Ryan Leckey <leckey.ryan@gmail.com>",
    "Austin Bonander <austin.bonander@gmail.com>"
]

[features]
default = [ "macros" ]
unstable = [ "sqlx-core/unstable" ]
postgres = [ "sqlx-core/postgres", "sqlx-macros/postgres" ]
mariadb = [ "sqlx-core/mariadb", "sqlx-macros/mariadb" ]
macros = [ "sqlx-macros", "proc-macro-hack" ]
uuid = [ "sqlx-core/uuid", "sqlx-macros/uuid" ]

[dependencies]
sqlx-core = { version = "0.1.0-pre", path = "sqlx-core" }
sqlx-macros = { version = "0.1.0-pre", path = "sqlx-macros", optional = true }
proc-macro-hack = { version = "0.5.11", optional = true }

[dev-dependencies]
async-std = { version = "1.2.0", features = [ "attributes" ] }
dotenv = "0.15.0"
matches = "0.1.8"
criterion = "0.3.0"

[[test]]
name = "macros"
required-features = [ "postgres", "uuid", "macros" ]

[[test]]
name = "postgres-types"
required-features = [ "postgres" ]

[[test]]
name = "mysql-types"
required-features = [ "mariadb" ]

[[bench]]
name = "postgres-protocol"
required-features = [ "postgres", "unstable" ]
harness = false
