[workspace]
members = [
    ".",
    "examples/todo",
    "examples/contacts"
]

[package]
name = "sqlx"
version = "0.0.0"
authors = ["Ryan Leckey <leckey.ryan@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "Asynchronous and expressive database client in pure Rust."
edition = "2018"

[features]
default = []
postgres = []
mariadb = []

[dependencies]
bitflags = "1.1.0"
byteorder = "1.3.2"
bytes = "0.4.12"
crossbeam-queue = "0.1.2"
enum-tryfrom = "0.2.1"
enum-tryfrom-derive = "0.2.1"
failure = "0.1.5"
futures-preview = "=0.3.0-alpha.17"
hex = "0.3.2"
itoa = "0.4.4"
log = "0.4.8"
md-5 = "0.8.0"
memchr = "2.2.1"
runtime = { version = "=0.3.0-alpha.6", default-features = false }

[dev-dependencies]
runtime = { version = "=0.3.0-alpha.6", default-features = true }
