[package]
name = "sqlx-core"
version = "0.6.0-pre"
repository = "https://github.com/launchbadge/sqlx"
description = "Core of SQLx, the Rust SQL Toolkit."
license = "MIT OR Apache-2.0"
edition = "2018"
readme = "README.md"
keywords = []
categories = []
authors = [
    "LaunchBadge <contact@launchbadge.com>"
]

[package.metadata.docs.rs]
# > RUSTDOCFLAGS="--cfg doc_cfg" cargo +nightly doc --all-features --no-deps --open
all-features = true
rustdoc-args = ["--cfg", "doc_cfg"]

[features]
default = []

# blocking (std) runtime
blocking = []

# abstract async feature
# not meant to be used directly
# activates several crates used in all async runtimes
async = ["futures-util"]

# async runtimes
async-std = ["async", "_async-std"]
actix = ["async", "actix-rt", "tokio_02"]
tokio = ["async", "_tokio"]

[dependencies]
actix-rt = { version = "1.1.1", optional = true }
_async-std = { version = "1.8.0", optional = true, package = "async-std" }
futures-util = { version = "0.3.8", optional = true }
_tokio = { version = "1.0.1", optional = true, package = "tokio", features = ["net"] }
tokio_02 = { version = "0.2.24", optional = true, package = "tokio", features = ["net"] }
url = "2.2.0"
