[package]
name = "sqlx-core"
version = "0.1.0-pre"
license = "MIT OR Apache-2.0"
description = "The Rust SQL Toolkit."
edition = "2018"
authors = [
    "Ryan Leckey <leckey.ryan@gmail.com>",
    "Austin Bonander <austin.bonander@gmail.com>"
]

[features]
default = []
unstable = []
postgres = []
mariadb = []

[dependencies]
async-std = { version = "1.2.0", default-features = false, features = [ "unstable" ] }
async-stream = "0.2.0"
bitflags = "1.2.1"
byteorder = { version = "1.3.2", default-features = false }
chrono = { version = "0.4", optional = true }
futures-channel = "0.3.1"
futures-core = "0.3.1"
futures-util = "0.3.1"
log = "0.4.8"
md-5 = "0.8.0"
memchr = "2.2.1"
url = "2.1.0"
uuid = { version = "0.8.1", optional = true }

[dev-dependencies]
matches = "0.1.8"
bytes = "0.5.2"
async-std = { version = "1.2.0", default-features = false, features = [ "attributes" ] }
