[package]
name = "sqlx-macros"
version = "0.2.0"
repository = "https://github.com/launchbadge/sqlx"
description = "Macros for SQLx, the rust SQL toolkit. Not intended to be used directly."
license = "MIT OR Apache-2.0"
edition = "2018"
authors = [
    "Ryan Leckey <leckey.ryan@gmail.com>", # ryan@launchbadge.com
    "Austin Bonander <austin.bonander@gmail.com>", # austin@launchbadge.com
    "Zachery Gyurkovitz <zgyurkovitz@gmail.com>", # zach@launchbadge.com
    "Daniel Akhterov <akhterovd@gmail.com>", # daniel@launchbadge.com
]

[lib]
proc-macro = true

[features]
default = []

runtime-async-std = [ "sqlx/runtime-async-std", "async-std" ]
runtime-tokio = [ "sqlx/runtime-tokio", "tokio", "once_cell" ]

# database
mysql = [ "sqlx/mysql" ]
postgres = [ "sqlx/postgres" ]

# type
chrono = [ "sqlx/chrono" ]
uuid = [ "sqlx/uuid" ]

[dependencies]
async-std = { version = "1.4.0", default-features = false, optional = true }
tokio = { version = "0.2", optional = true }
once_cell = { version = "1.3", optional = true }
dotenv = { version = "0.15.0", default-features = false }
futures = { version = "0.3.1", default-features = false, features = ["executor"] }
proc-macro2 = { version = "1.0.6", default-features = false }
sqlx = { version = "0.2.0", default-features = false, path = "../sqlx-core", package = "sqlx-core" }
syn = { version = "1.0.11", default-features = false, features = [ "full" ] }
quote = { version = "1.0.2", default-features = false }
url = { version = "2.1.0", default-features = false }
lazy_static = "1.4.0"
