[package]
name = "sqlx-macros"
version = "0.1.0-pre"
authors = ["Austin Bonander <austin.bonander@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
async-std = "1.2.0"
dotenv = "0.15.0"
futures = "0.3.1"
proc-macro-hack = "0.5.11"
proc-macro2 = "1.0.6"
sqlx = { version = "0.1.0-pre", path = "../sqlx-core", package = "sqlx-core" }
syn = { version = "1.0.11", default-features = false }
quote = "1.0.2"
url = "2.1.0"

[features]
chrono = ["sqlx/chrono"]
mysql = ["sqlx/mysql"]
postgres = ["sqlx/postgres"]
uuid = ["sqlx/uuid"]
