[package]
name = "sqlx-macros"
version = "0.1.0"
authors = ["Austin Bonander <austin.bonander@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
dotenv = "0.15.0"
futures-preview = "0.3.0-alpha.18"
proc-macro2 = "1.0.6"
sqlx = { path = "../" }
syn = "1.0"
quote = "1.0"
tokio = { version = "0.2.0-alpha.4" }
url = "2.1.0"

[features]
postgres = ["sqlx/postgres"]
uuid = ["sqlx/uuid"]
